### PR TITLE
add kcc and mojitoswap

### PR DESCRIPTION
**Pull request by mhxw**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Blockchain Submissions:
We'll need the following to integrate your **EVM-compatible** blockchain: 

- [x] At least one AMM on your chain with a daily volume over $100k. Do you include it in your PR?   
- [x] Your chain logo
- [x] Your native token logo
- [x] Blockexplorer that could open account and transactions pages 
- [x] High-performance RPC endpoint. Raise the issue in this repo or reach out our team at [Discord](https://discord.com/invite/dPW8fzwzz9) with access details.  

### New AMM Submissions:
We'll need the following to integrate your AMM: 

* [x] Do you have a daily trading volume over $20k? 
* [x] Does "type" at AMM config match your code base? 
* [x] Your AMM logo. Please add a link to your logo or attach it to a new issue in this repo.  

- chain logo: https://user-images.githubusercontent.com/32643286/228192841-657352c1-3ac7-412e-8cb6-208f7852e104.svg
- chain logo source: https://docs.kcc.io/disclosure/media-kit
- native token logo: https://static-nft.mojitoswap.finance/token/kcs.png
- amm logo:   https://static.kcc.network/boss/images/a2e51aa379d642ce94828bf54a0515cf-mojito-swap.jpg

### CODE REVIEW

**Comment by evahteev** [comment]
@mhxw Testing in our staging environment, merging after

**Comment by mhxw** [comment]
> 

Hi @evahteev , Where's your staging environment?

**Comment by mhxw** [comment]
> @mhxw Unfortunately it's internal, but all looks good, can you please provide a tokens list we can trust to label ERC-20 tokens verified based on that? Thanks.

https://app.mojitoswap.finance/info

**Comment by evahteev** [comment]
> > @mhxw Unfortunately it's internal, but all looks good, can you please provide a tokens list we can trust to label ERC-20 tokens verified based on that? Thanks.
> 
> https://app.mojitoswap.finance/info/tokens

@mhxw 
Maybe you have in tokens list standard? like https://tokens.coingecko.com/canto/all.json thanks, it would help a lot.

**Pull request merged**
