### PR TITLE
feat(dapps): add melegaswap

### PR DESCRIPTION
**Pull request by developerdavi**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New AMM Submissions:
We'll need the following to integrate your AMM: 

* [x] Do you have a daily trading volume over $20k? 
* [x] Does "type" at AMM config match your code base? 
* [x] Your AMM logo. Please add a link to your logo or attach it to a new issue in this repo.

Link to MelegaSwap's logo: https://melega.devdavi.io/logo.png

### CODE REVIEW

**Comment by developerdavi** [comment]
@sneg55
@VitalyVakhteev
@evahteev

Can someone please review this PR?

**Comment by developerdavi** [comment]
@Kharabet

**Comment by evahteev** [comment]
@developerdavi In staging env, checking if it goes ok. Thanks for your commitment!

**Comment by evahteev** [comment]
@developerdavi Goes into our production next deployment on merge.

**Review by evahteev — APPROVED** [review]

**Pull request merged**
